### ISSUE TITLE
Unable to add targets

### ISSUE THREAD

**Issue by Davincible** [hassio-addons/addon-prometheus#45]
Created a `alderson.yml` file under the targets dir, but the target does not get picked up

```yaml
---
job_name: 'alderson'
honor_timestamps: true
scrape_interval: 15s
scrape_timeout: 10s
metrics_path: /metrics
scheme: http
static_configs:
- targets:
  - 192.168.88.48:9100
```

Any idea why it's not picking it up? The logs don't give any errors
