### ISSUE TITLE
Unable to edit prometheus.yml configuration via web interface.

### ISSUE THREAD

**Issue by traylenator** [hassio-addons/addon-prometheus#8]
# Problem/Motivation

Trying to read metrics from home assistant I am unable. In particular seems no way to edit the configuration 
prometheus.yml file.

Background I'm just trying to set up this addon and prometheus history component.

I'm not seeing any metrics in promethesus with a integration config of 

```yaml
namespace: 245b
component_config_glob:
  sensor.*temp*:
    override_metric: temperature_c
filter:
  include_entities:
    - sensor.ben_temperature_temperature
```

https://www.home-assistant.io/integrations/prometheus/

I wanted to add the scrape config which I think should be.

```
- job_name: "hass"
    scrape_interval: 60s
    metrics_path: /api/prometheus
    scheme: https
    static_configs:
      - targets: ['HOSTNAME:8123']
  ```
as the default config has a scrape of `/core/api/prometheus` only 

## Expected behavior

Should be able to edit `prometheus.yml` via supervisor web interface.

## Actual behavior

There is no configuration to edit.

Configuration is there in the running docker image `/etc/prometheus/prometheus.yml` but cannot be edited.

## Steps to reproduce

Install prometheus addon , go to configuration tab. See attached screen shot.

![image](https://user-images.githubusercontent.com/135205/108081760-9b0f0400-7071-11eb-8831-5bdfddaa2384.png)

Prometheus addon - 1.0.0-beta.0 
Core version - core-2021.2.3
supervisor-2021.02.9
Home Assistant OS 5.11
